<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://relaxng.org/ns/structure/1.0"?>
<package format="3">
  <name>f_drone_gazebo</name>
  <version>0.1.0</version>
  <description>Gazebo worlds and custom system plugins (DroneSerial, DroneWorld, DroneAutoSim) for the F-Drone quadrotor.</description>
  <maintainer email="mtglucas1@gmail.com">Lucas Wendland</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>f_drone_description</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
