name=micro_ros_f_drone
version=1.0.0-humble
author=CursedRock17
maintainer=Lucas Wendland <lwendlan@umd.edu>
sentence= micro-ROS FDrone Arduino library
paragraph= micro-ROS FDrone Arduino library
url=https://github.com/CursedRock17/F-Drone-Stack/tree/humble/FlightComputer/micro_ros_f_drone
category=Other
architectures=stm32,OpenCR,Teensyduino,samd,sam,mbed,esp32,mbed_portenta,mbed_giga,renesas_uno,mbed_opta
